### ISSUE TITLE
let user define their  process completed key word

### ISSUE THREAD

**Issue by danie1Lin** [rickstaa/tmux-notify#22] opened 2021-11-04 04:51 UTC
**Is your feature request related to a problem? Please describe.**
At first, I found it did not work on my terminal. Then I looked into the script. I found we use # or $ to check the process if it is stopped.
[here](https://github.com/ChanderG/tmux-notify/blob/master/scripts/notify.sh#L62)
But my command line is like 🤣
![image](https://user-images.githubusercontent.com/13273358/140259207-de589120-74b7-4635-9f04-5eea256b11d7.png)

**Describe the solution you'd like**
If my understanding of the `notify.sh` is correct. We might let it be a customizable variable to capture the completed event.

**Comment by rickstaa** [comment] 2021-11-04 08:48
@danie1Lin Thanks for your feature request. We are indeed missing the `%` symbol that is used by the `csh` shell. Originally we only looked for the regular user indicator (i.e. `$`) but @ChanderG added support for the root user indicator (i.e. `#`) in https://github.com/ChanderG/tmux-notify/commit/2aa2e2f191084148e4a9cd8c0da14737a91e6876. 

I think adding `%` to [this line](https://github.com/ChanderG/tmux-notify/blob/master/scripts/notify.sh#L62) list will solve the problem for most users. I think the `csh` prompt suffix should be included by default.  

```bash
"$" | "#" | "%")
``` 

Apart from that, I have no problem adding a variable to specify additional prompt separators (e.g. `@tnotify-promp-suffix`). I am, however, not sure for how many users such a variable would be helpful. Do you currently use shells with other prop prefixes? Since most shells use the `$`, `#` and `%` separators, I think such a use case only happens when a user changes the `PS1` variable. @ChanderG, what do you think?

**Comment by rickstaa** [comment] 2021-11-04 09:05
@danie1Lin A fix for the bug you were experiencing is shipped in [v1.2.0](https://github.com/ChanderG/tmux-notify/releases/tag/v1.2.0). Can you verify whether it works on your system?

I will keep this issue open so that we can discuss whether we want to also add a `@tnotify-promp-suffix` variable.

**Comment by danie1Lin** [comment] 2021-11-08 06:19
Thank you for fast-developing this feature, @rickstaa!
I am using zsh. It is the theme of zsh modifying the $ps1 to `%`. I think it is quite common some themes will have many different types `$PS1`, and It is getting more complicated like [p10k](https://github.com/romkatv/powerlevel10k). Though, costuming the variable can resolve most of the situations. For now, It does solve my problem, thank you!

**Comment by rickstaa** [comment] 2021-11-08 11:27
@danie1Lin Thanks for your response and the use case. I added the `@tnotify-prompt-suffixes` variable to #24. The new version seems to work on my system. Can you please test to see if it works on your system? For example by using the [https://github.com/romkatv/powerlevel10k](https://github.com/romkatv/powerlevel10k) you mentioned.

I asked @ChanderG to review the pull request since it contains a significant change. If @ChanderG approves my pull request I will merge it under `v1.3.0`

**Comment by danie1Lin** [comment] 2021-11-10 08:01
Hi @rickstaa, I tested #24. But sorry about the bad news, it does not work on p10k when the $PS1 like this, the capture of the last character will be the last character of time. Maybe we should consider regexp?
![image](https://user-images.githubusercontent.com/13273358/141073081-9d59665f-69fa-400d-ab40-8b532b1dd9e4.png)

**Comment by rickstaa** [comment] 2021-11-10 08:11
@danie1Lin Thanks a lot for testing my solution! Interesting, what is the literal version of your PS1 in that case? Is it `&#9656;` or `~`? What solution with regex do you have in mind?

Feel free to create a pull request on #24 if you think that is faster than explaining it here. The code can be debugged using breakpoints with the [vscode bash extension](https://marketplace.visualstudio.com/items?itemName=mads-hartmann.bash-ide-vscode) using the following steps:
- Replace the branch that is active in the `/home/username/.tmux/plugins/tmux-notify`.
- Open vscode.
- Open tmux in the integrated terminal.
- Start the debug session on the script you want to debug.
- The debugger should then stop on the breakpoints.

**Comment by rickstaa** [comment] 2022-01-05 09:12
@danie1Lin I am currently not able to reproduce the problems you are experiencing.  Did you see my previous questions?

**Comment by kohane27** [comment] 2023-04-19 06:33
Hello guys, I was wondering why `tmux-notify` was not working and I found this issue.

I'm using [starship](https://starship.rs/) prompt that looks like below:

![tmux-notify](https://user-images.githubusercontent.com/57322459/232986370-4f60d42c-89c1-456e-b8fb-999bac25316c.png)

As suggested in the above comment, I tried the following solution:

```
"$" | "#" | "%" | "➜")
```

but it doesn't work. Any input is much appreciated. Thank you!

**Comment by rickstaa** [comment] 2023-04-24 13:59
> Hello guys, I was wondering why `tmux-notify` was not working and I found this issue.
> 
> I'm using [starship](https://starship.rs/) prompt that looks like below:
> 
> ![tmux-notify](https://user-images.githubusercontent.com/57322459/232986370-4f60d42c-89c1-456e-b8fb-999bac25316c.png)
> 
> As suggested in the above comment, I tried the following solution:
> 
> ```
> "$" | "#" | "%" | "➜")
> ```
> 
> but it doesn't work. Any input is much appreciated. Thank you!

Hey @kohane27. Could you maybe check if https://github.com/ChanderG/tmux-notify/pull/24 solves your problem? I created that PR some time ago but since @danie1Lin didn't respond, did not merge it since I was uncertain if it worked. I'm happy to merge that pull request if it works for you 👍🏻.

**Comment by rickstaa** [comment] 2023-05-13 11:09
@danie1Lin and @kohane27 this feature was released under https://github.com/ChanderG/tmux-notify/pull/24. You can now set the bash prefix of your choice using the following tmux config command:

```bash
set -g @tnotify-prompt-suffixes '➜'
```

**Comment by kohane27** [comment] 2023-05-13 12:09
Hello @rickstaa ,

Hope you're doing well.

Apologies for not checking the fix from the earlier msg.

I have just updated `tmux-notify` and I'm very happy to report that it's working!

![2023-05-13-20-05-52](https://github.com/ChanderG/tmux-notify/assets/57322459/17631b64-88dc-44a6-af65-e77ee57f1e3e)



It's really handy to be notified about some long running processes.

Thank you so much and have a good day!

**Comment by cometta** [comment] 2023-08-24 00:52
![image](https://github.com/rickstaa/tmux-notify/assets/187495/18f7c50d-8ee9-4cb7-8320-b8e321d40d58)

i'm using zsh, may i know what should i set for tnotify-prompt-suffixes as my prompt look like above

**Comment by rickstaa** [comment] 2023-08-24 07:04
@cometta I do not know by head which symbols are used to create that prompt. Can you please give me the result of `echo $PS1`?

**Comment by cometta** [comment] 2023-08-24 07:26
echo $PS1
```
$(kube_ps1)%{%f%b%k%}$(build_prompt)
```

**Comment by rickstaa** [comment] 2023-08-24 07:49
> echo $PS1
> 
> ```
> $(kube_ps1)%{%f%b%k%}$(build_prompt)
> ```

Ah, the symbol you are looking for is the last character returned by the `build_prompt` function. You could try to print the results of `$(build_prompt)` to see if this function is in the global scope. What customizations are you using in your .zshrc file? When I use the zsh shell, I use https://ohmyz.sh/.

**Comment by cometta** [comment] 2023-08-24 07:53
echo $(build_prompt)
```
%{%K{black}%}%{%F{default}%} %(!.%{%F{yellow}%}.)%n@%m %{%K{blue}%F{black}%}%{%F{black}%} %~ %{%k%F{blue}%}%{%f%}
```

yes i'm using https://ohmyz.sh/. as well

**Comment by rickstaa** [comment] 2023-08-24 09:17
> echo $(build_prompt)
> 
> ```
> %{%K{black}%}%{%F{default}%} %(!.%{%F{yellow}%}.)%n@%m %{%K{blue}%F{black}%}%{%F{black}%} %~ %{%k%F{blue}%}%{%f%}
> ```
> 
> yes i'm using https://ohmyz.sh/. as well

Ah, I think this is the setup you're using:

- **Shell:** zsh
- **Configuration:** [Oh My Zsh](https://ohmyz.sh/)
- **Theme:** agnoster

The `agnoster` theme involves intricate PS1 modifications not currently monitored by the `tmux-notify` plugin. To address this, you need to focus on the prompt suffix defined in the following function block:

```bash
Main prompt
build_prompt() {
  RETVAL=$?
  prompt_status
  prompt_context
  prompt_dir
  prompt_git
  prompt_end
}
```

Source: [agnoster.zsh-theme](https://github.com/ohmyzsh/ohmyzsh/blob/6e85ff5b44e81f5b9d743b6ba1df7ed7b62dc2df/themes/agnoster.zsh-theme#L112)

This suffix is dynamically generated through the `prompt_end` function. To access the current suffix for a specific directory, you can use the `SEGMENT_SEPERATOR` symbol:

```bash
SEGMENT_SEPARATOR='⮀'
```

Source: [agnoster.zsh-theme](https://github.com/ohmyzsh/ohmyzsh/blob/6e85ff5b44e81f5b9d743b6ba1df7ed7b62dc2df/themes/agnoster.zsh-theme#L29C1-L29C18)

For your scenario, you should set the following in your Tmux configuration:

```bash
set -g @tnotify-prompt-suffixes ''
```

If you also want to support bash, you can specify multiple suffixes:

```bash
set -g @tnotify-prompt-suffixes ',$'
```

**Comment by rickstaa** [comment] 2023-08-24 09:31
@cometta I created https://github.com/rickstaa/tmux-notify/discussions/52 for future reference. Please let me know if it also works on your side so that we can close this issue 👍🏻.

**Comment by cometta** [comment] 2023-08-24 10:20
it works. thank you

**Closed** 2023-08-24 10:52 UTC
